[package]
name = "realm-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
byteorder = "1.5.0"
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
hex = "0.4.3"
log = "0.4.27"
memmap2 = "0.9.5"
pretty_env_logger = "0.5.0"
tracing = { version = "0.1.41", features = ["std", "log"] }
