name: Publish Crate

on:
  push:
    tags:
      - "v*.*.*" # This triggers the action for tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Run Tests
        run: cargo test --release

      - name: Verify Formatting
        run: cargo fmt --check

      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
