name: Publish Crate

on:
  push:
    tags:
      - "v*.*.*" # This triggers the action for tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: rust-toolchain

      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
