name: Validate Crate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Run Tests
        run: cargo test --release

      - name: Verify Formatting
        run: cargo fmt --check
