name: Validate Crate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: rust-toolchain

      - name: Build
        run: cargo build --release

      - name: Run Tests
        run: cargo test --release

      - name: Verify Formatting
        run: cargo fmt --check
